### ISSUE TITLE
Problem yii\i18n\DbMessageSource

### ISSUE THREAD

**Issue by ToSchQLB** [w3lifer/yii2-i18n-js#5]
By using yii\i18n\DbMessageSource i get the following error:
Unknown Property – yii\base\UnknownPropertyException

Reason: DbMessageSource has no basePath Property

yii\base\UnknownPropertyException: Getting unknown property: yii\i18n\DbMessageSource::basePath in /var/www/dev.example/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/dev.example/vendor/w3lifer/yii2-i18n-js/I18nJs.php(95): yii\base\Component->__get()
#1 /var/www/dev.example/vendor/w3lifer/yii2-i18n-js/I18nJs.php(65): w3lifer\yii2\I18nJs::getBasePaths()
#2 /var/www/dev.example/vendor/yiisoft/yii2/base/BaseObject.php(109): w3lifer\yii2\I18nJs->init()
#3 [internal function]: yii\base\BaseObject->__construct()
#4 /var/www/dev.example/vendor/yiisoft/yii2/di/Container.php(392): ReflectionClass->newInstanceArgs()
#5 /var/www/dev.example/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build()
#6 /var/www/dev.example/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#7 /var/www/dev.example/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject()
#8 /var/www/dev.example/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get()
#9 /var/www/dev.example/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get()
#10 /var/www/dev.example/themes/greydance/layouts/main.php(37): yii\di\ServiceLocator->__get()
#11 /var/www/dev.example/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/dev.de...')
#12 /var/www/dev.example/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#13 /var/www/dev.example/vendor/yiisoft/yii2/base/Controller.php(401): yii\base\View->renderFile()
#14 /var/www/dev.example/vendor/yiisoft/yii2/base/Controller.php(387): yii\base\Controller->renderContent()
#15 /var/www/dev.example/controllers/SiteController.php(64): yii\base\Controller->render()
#16 [internal function]: app\controllers\SiteController->actionIndex()
#17 /var/www/dev.example/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#18 /var/www/dev.example/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#19 /var/www/dev.example/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction()
#20 /var/www/dev.example/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#21 /var/www/dev.example/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#22 /var/www/dev.example/web/index.php(16): yii\base\Application->run()
#23 {main}

**Comment by w3lifer** [comment]
This package only works with translations that are stored in files.
